name: Setup AWS Signer Notation CLI
description: Setup AWS Signer Notation CLI
author: rudderlabs

inputs:
  public-key:
    description: "Public key from AWS Signer"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download the Notation CLI installer
      shell: bash
      run: |
        echo "Installing Notation CLI for architecture: ${{ runner.arch }}"
        if [[ "${{ runner.arch }}" == "X64" ]]; then
          curl -fsSL \
          https://d2hvyiie56hcat.cloudfront.net/linux/amd64/installer/deb/latest/aws-signer-notation-cli_amd64.deb \
          -o notation.deb
          curl -fsSL \
          https://d2hvyiie56hcat.cloudfront.net/linux/amd64/installer/deb/latest/aws-signer-notation-cli_amd64.deb.sig \
          -o notation.deb.sig
        elif [[ "${{ runner.arch }}" == "ARM64" ]]; then
          curl -fsSL \
          https://d2hvyiie56hcat.cloudfront.net/linux/arm64/installer/deb/latest/aws-signer-notation-cli_arm64.deb \
          -o notation.deb
          curl -fsSL \
          https://d2hvyiie56hcat.cloudfront.net/linux/arm64/installer/deb/latest/aws-signer-notation-cli_arm64.deb.sig \
          -o notation.deb.sig
        else
          echo "Unsupported architecture: ${{ runner.arch }}"
          exit 1
        fi

    - name: Check the public key
      shell: bash
      run: |
        echo "Writing public key..."
        echo "${{ inputs.public-key }}" > public.key

        echo "Importing public key..."
        gpg --import public.key

        echo "Verifying Notation CLI signature..."
        gpg --verify notation.deb.sig notation.deb

    - name: Install Notation CLI
      shell: bash
      run: |
        echo "Installing Notation CLI..."
        sudo dpkg -i -E notation.deb
        notation version
        notation plugin ls
